<a href="https://colab.research.google.com/github/Naren221/NLP/blob/main/NarendraMDS202336_Assignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      Assignment 02


## **Narendra. C** <br> **MDS202336**

## 1. Implementing Modified Verison of COALS

* The preprocessed corpus is stored in JSON files, where each file contains a collection of documents.
* Each document in the JSON file is represented as a key-value pair:

    * The key is the document name or ID, which serves as a unique identifier for the document.
    * The value is the preprocessed text of that document, which consists of cleaned and tokenized words from the original text (e.g., lowercase, punctuation removed, stopwords removed).

* This structure allows easy access to both the document identifiers and their
corresponding preprocessed content, facilitating efficient data manipulation and analysis

In [ ]:
import gc
gc.collect()

0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Steps to Create a Co-occurrence Matrix

1. **Identify Data Sources**
   - Locate and list all relevant JSON files containing text data.

2. **Extract Vocabulary**
   - **Read Files:**
     - Read and parse text data from each JSON file.
   - **Build Vocabulary:**
     - Extract unique tokens from each file and aggregate them into a global vocabulary.
   - **Save Vocabulary:**
     - Save the vocabulary to a file for future reference.

3. **Initialize Co-occurrence Matrix**
   - **Prepare Matrix:**
     - Initialize a sparse matrix for storing co-occurrence counts based on the global vocabulary.

4. **Process Each File**
   - **Load Data:**
     - Read and parse text data from each JSON file.
   - **Update Matrix:**
     - Convert tokens to matrix indices using the global vocabulary.
     - Update the co-occurrence matrix based on token co-occurrences within a defined window size.

5. **Finalize Matrix**
   - **Ensure Symmetry:**
     - Make the matrix symmetric by adding its transpose.
   - **Convert Format:**
     - Change the matrix to a more efficient storage format for further use (e.g., CSR format).

6. **Save Results**
   - **Store Matrix:**
     - Save the matrix and vocabulary in a storage format for future use (e.g., HDF5 format).

7. **Clean Up**
   - Free up memory by deleting temporary data structures.


In [ ]:
import os
import json
from tqdm import tqdm

def extract_vocabulary(directory, output_path='/content/drive/MyDrive/vocabulary.txt'):
    # Get the list of JSON files in the directory
    json_files = [f for f in os.listdir(directory) if f.endswith('.json')]

    if not json_files:
        raise ValueError("No JSON files found in the directory.")

    # Initialize a set to store the vocabulary
    vocab = set()

    # Process each JSON file with a progress bar
    for json_file_name in tqdm(json_files, desc='Extracting vocabulary'):
        file_path = os.path.join(directory, json_file_name)

        # Read the JSON file
        with open(file_path, 'r') as file:
            data = json.load(file)

        # Collect unique tokens from the current file
        for document in data:
            vocab.update(document)

        # Free the data from memory
        del data

    # Save the vocabulary to a file
    with open(output_path, 'w') as file:
        for word in sorted(vocab):
            file.write(f"{word}\n")

    print(f"Vocabulary extracted and saved to: {output_path}")

# Example usage
directory = '/content/drive/MyDrive/NLP Assignments/preprocessed_files/'
output_path = '/content/drive/MyDrive/NLP Assignments/vocabulary.txt'
extract_vocabulary(directory, output_path=output_path)


Extracting vocabulary: 100%|██████████| 12/12 [01:17<00:00,  6.46s/it]


Vocabulary extracted and saved to: /content/drive/MyDrive/vocabulary.txt


In [31]:
from google.colab import drive
drive.mount('/content/drive')

import os
import json
import numpy as np
import scipy.sparse as sp
import h5py
from tqdm import tqdm

# Load vocabulary
def load_vocabulary(vocab_path):
    with open(vocab_path, 'r') as file:
        vocab = [line.strip() for line in file]
    return vocab

# Function to process a single JSON file and build its co-occurrence matrix
def process_single_file(file_path, vocab_index, window_size, output_path):
    vocab_size = len(vocab_index)
    cooccurrence_matrix = sp.lil_matrix((vocab_size, vocab_size), dtype=np.float32)

    # Read the JSON file
    with open(file_path, 'r') as file:
        data = json.load(file)

    # Process each document in the current JSON file with a progress bar
    with tqdm(total=len(data), desc=f'Processing {os.path.basename(file_path)}') as pbar:
        for document in data:
            token_indices = [vocab_index[token] for token in document if token in vocab_index]

            for i, token_idx in enumerate(token_indices):
                start_index = max(0, i - window_size)
                end_index = min(len(token_indices), i + window_size + 1)

                # Update co-occurrence for previous and future tokens without weights
                for j in range(start_index, i):
                    cooccurrence_matrix[token_idx, token_indices[j]] += 1

                for j in range(i + 1, end_index):
                    cooccurrence_matrix[token_idx, token_indices[j]] += 1

            pbar.update(1)

    # Convert to CSR format for efficient storage
    cooccurrence_matrix_csr = cooccurrence_matrix.tocsr()

    # Store the matrix in a file
    output_file = os.path.join(output_path, f'cooccurrence_matrix_{os.path.basename(file_path).split(".")[0]}.h5')
    with h5py.File(output_file, 'w') as f:
        f.create_dataset('data', data=cooccurrence_matrix_csr.data, compression='gzip')
        f.create_dataset('indices', data=cooccurrence_matrix_csr.indices, compression='gzip')
        f.create_dataset('indptr', data=cooccurrence_matrix_csr.indptr, compression='gzip')
        f.attrs['shape'] = cooccurrence_matrix_csr.shape

    # Free memory
    del cooccurrence_matrix
    del cooccurrence_matrix_csr
    del data

    print(f"Co-occurrence matrix for {file_path} stored at: {output_file}")
    return output_file

def process_json_file(json_file_path, vocab_path, output_path, window_size=4):
    vocab = load_vocabulary(vocab_path)
    vocab_index = {word: i for i, word in enumerate(vocab)}

    # Process and store co-occurrence matrix for the specified JSON file
    process_single_file(json_file_path, vocab_index, window_size, output_path)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
# file_number =  3 # Replace with the desired file number

for file_number in [5, 6, 7]:
  json_file_path = f'/content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_{file_number}.json'  # Path to your specific JSON file
  directory = '/content/drive/MyDrive/NLP Assignments/preprocessed_files/'
  vocab_path = '/content/drive/MyDrive/NLP Assignments/vocabulary.txt'
  output_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/'

  process_json_file(json_file_path, vocab_path, output_path)


Processing chunk_5.json: 100%|██████████| 4711/4711 [23:00<00:00,  3.41it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_5.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_5.h5


Processing chunk_6.json: 100%|██████████| 4711/4711 [23:07<00:00,  3.39it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_6.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_6.h5


Processing chunk_7.json: 100%|██████████| 4711/4711 [22:10<00:00,  3.54it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_7.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_7.h5


In [8]:
for file_number in [8, 9, 10]:
  json_file_path = f'/content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_{file_number}.json'  # Path to your specific JSON file
  directory = '/content/drive/MyDrive/NLP Assignments/preprocessed_files/'
  vocab_path = '/content/drive/MyDrive/NLP Assignments/vocabulary.txt'
  output_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/'

  process_json_file(json_file_path, vocab_path, output_path)

Processing chunk_8.json: 100%|██████████| 4711/4711 [21:41<00:00,  3.62it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_8.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_8.h5


Processing chunk_9.json: 100%|██████████| 4711/4711 [23:04<00:00,  3.40it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_9.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_9.h5


Processing chunk_10.json: 100%|██████████| 4711/4711 [24:27<00:00,  3.21it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_10.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_10.h5


In [3]:
for file_number in [11,12]:
  json_file_path = f'/content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_{file_number}.json'  # Path to your specific JSON file
  directory = '/content/drive/MyDrive/NLP Assignments/preprocessed_files/'
  vocab_path = '/content/drive/MyDrive/NLP Assignments/vocabulary.txt'
  output_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/'

  process_json_file(json_file_path, vocab_path, output_path)

Processing chunk_11.json: 100%|██████████| 4711/4711 [15:33<00:00,  5.05it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_11.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_11.h5


Processing chunk_12.json: 100%|██████████| 4707/4707 [14:34<00:00,  5.38it/s]


Co-occurrence matrix for /content/drive/MyDrive/NLP Assignments/preprocessed_files/chunk_12.json stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/cooccurrence_matrix_chunk_12.h5


* I built a cooccurrence matrix for each chunk of the corpus.
* This was done to manage tasks with limited memory.
* Now i will combine these matrices to form a single cooccurrence matrix for the entire corpus.

In [2]:
import os
import scipy.sparse as sp
import h5py
from tqdm import tqdm

# Function to incrementally combine matrices and write them to disk
def combine_cooccurrence_matrices_incrementally(folder_path, vocab_size, output_file):
    final_matrix = None

    # Get all .h5 files in the folder
    matrix_files = [f for f in os.listdir(folder_path) if f.startswith('cooccurrence_matrix') and f.endswith('.h5')]
    if not matrix_files:
        raise ValueError("No co-occurrence matrix files found in the folder.")

    # Combine each matrix into the final matrix incrementally
    for file in tqdm(matrix_files, desc="Combining matrices"):
        file_path = os.path.join(folder_path, file)

        with h5py.File(file_path, 'r') as f:
            data = f['data'][:]
            indices = f['indices'][:]
            indptr = f['indptr'][:]
            shape = f.attrs['shape']

        cooccurrence_matrix = sp.csr_matrix((data, indices, indptr), shape=shape)

        # If final_matrix is None (i.e., first matrix), set it. Otherwise, add the new matrix
        if final_matrix is None:
            final_matrix = cooccurrence_matrix
        else:
            final_matrix = final_matrix + cooccurrence_matrix

        # After processing each matrix, save intermediate results to avoid memory overload
        _save_intermediate(final_matrix, output_file)
        print(f"\nProcessed {file} and saved intermediate result.")

    # Return the final matrix
    return final_matrix

# Helper function to save intermediate results
def _save_intermediate(matrix, output_file):
    with h5py.File(output_file, 'w') as f:
        f.create_dataset('data', data=matrix.data, compression='gzip')
        f.create_dataset('indices', data=matrix.indices, compression='gzip')
        f.create_dataset('indptr', data=matrix.indptr, compression='gzip')
        f.attrs['shape'] = matrix.shape

    print(f"Intermediate result saved to: {output_file}")

# Function to store the final combined matrix
def store_final_matrix(final_matrix, folder_path):
    final_output_path = os.path.join(folder_path, 'final_cooccurrence_matrix.h5')
    _save_intermediate(final_matrix, final_output_path)
    print(f"Final co-occurrence matrix stored at: {final_output_path} 🎉")


In [3]:
folder_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices'  # Folder where matrices are hanging out
vocab_size = len(load_vocabulary('/content/drive/MyDrive/NLP Assignments/vocabulary.txt'))  # Load your vocab size
output_file = '/content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5'  # Path to store the intermediate/final matrix

# Call the function to combine matrices incrementally
final_matrix = combine_cooccurrence_matrices_incrementally(folder_path, vocab_size, output_file)

# After processing, you can store the final result
store_final_matrix(final_matrix, '/content/drive/MyDrive/NLP Assignments/Assignment_02')


Combining matrices:   8%|▊         | 1/12 [00:12<02:12, 12.01s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_3.h5 and saved intermediate result.


Combining matrices:  17%|█▋        | 2/12 [00:31<02:41, 16.16s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_1.h5 and saved intermediate result.


Combining matrices:  25%|██▌       | 3/12 [00:56<03:03, 20.41s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_2.h5 and saved intermediate result.


Combining matrices:  33%|███▎      | 4/12 [01:26<03:12, 24.01s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_4.h5 and saved intermediate result.


Combining matrices:  42%|████▏     | 5/12 [02:02<03:20, 28.62s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_5.h5 and saved intermediate result.


Combining matrices:  50%|█████     | 6/12 [02:44<03:17, 32.91s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_6.h5 and saved intermediate result.


Combining matrices:  58%|█████▊    | 7/12 [03:28<03:03, 36.76s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_7.h5 and saved intermediate result.


Combining matrices:  67%|██████▋   | 8/12 [04:16<02:41, 40.40s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_8.h5 and saved intermediate result.


Combining matrices:  75%|███████▌  | 9/12 [05:10<02:13, 44.46s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_9.h5 and saved intermediate result.


Combining matrices:  83%|████████▎ | 10/12 [06:09<01:38, 49.01s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_10.h5 and saved intermediate result.


Combining matrices:  92%|█████████▏| 11/12 [07:11<00:52, 52.92s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_11.h5 and saved intermediate result.


Combining matrices: 100%|██████████| 12/12 [08:14<00:00, 41.17s/it]

Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/output_matrices/final_cooccurrence_matrix_intermediate.h5

Processed cooccurrence_matrix_chunk_12.h5 and saved intermediate result.


Intermediate result saved to: /content/drive/MyDrive/NLP Assignments/Assignment_02/final_cooccurrence_matrix.h5
Final co-occurrence matrix stored at: /content/drive/MyDrive/NLP Assignments/Assignment_02/final_cooccurrence_matrix.h5 🎉


In [2]:
import h5py
import numpy as np
import scipy.sparse as sp

def view_submatrix(file_path, row_start, col_start, size=5):
    with h5py.File(file_path, 'r') as f:
        data = f['data'][:]
        indices = f['indices'][:]
        indptr = f['indptr'][:]
        shape = f.attrs['shape']

        # Create the CSR matrix from the stored data
        cooccurrence_matrix = sp.csr_matrix((data, indices, indptr), shape=shape)

        # Extract the submatrix
        submatrix = cooccurrence_matrix[row_start:row_start + size, col_start:col_start + size].toarray()

        print("10x10 Submatrix:")
        print(submatrix)

file_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/final_cooccurrence_matrix.h5'
view_submatrix(file_path, row_start=0, col_start=0)


10x10 Submatrix:
[[4.116e+03 4.900e+01 4.000e+00 1.000e+00 0.000e+00]
 [4.900e+01 1.600e+02 5.000e+00 2.000e+00 0.000e+00]
 [4.000e+00 5.000e+00 3.400e+01 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 1.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.000e+00 0.000e+00 0.000e+00]]


In [7]:
vocab_path = '/content/drive/MyDrive/NLP Assignments/vocabulary.txt'
vocab = load_vocabulary(vocab_path)
print(len(vocab))

1470595


In [25]:
type(vocab)


list

## Now i will try to reduce the size of the vocabulary to 7000.

### I am reducing the vocabulary size by **filtering out infrequent words**, specifically those that have **low co-occurrence frequencies**. Additionally, stop words will be removed. This optimization aims to enhance the co-occurrence matrix and improve overall efficiency.


### Reason for Reducing Vocabulary Size This Way

* Reducing vocabulary size based on **co-occurrence frequency** helps prioritize words that frequently appear together, capturing more meaningful word relationships.
* Filtering out terms with low co-occurrence reduces noise and leads to a more efficient, less sparse co-occurrence matrix, improving computational performance.
* This method emphasizes relationships between words rather than individual token frequency, offering a more insightful analysis of the text.
* The approach focuses on selecting the **top 7000** words based on co-occurrence frequency, ensuring that significant terms are retained while less informative ones are removed.


In [24]:
import json
from nltk.probability import FreqDist
from tqdm import tqdm

# Initialize frequency distribution
def process_chunk(chunk_file):
    freq_dist = FreqDist()

    with open(chunk_file, 'r') as file:
        token_lists = json.load(file)

    for token_list in token_lists:
        freq_dist.update(token_list)

    return freq_dist

# Path to the folder where token chunks are stored
chunks_folder = '/content/drive/MyDrive/NLP Assignments/preprocessed_files'
chunk_files = [f'{chunks_folder}/chunk_{i}.json' for i in range(1, 13)]  # Assuming 12 chunks

# Process chunks sequentially
final_freq_dist = FreqDist()
for chunk_file in tqdm(chunk_files, desc="Processing chunks"):
    freq_dist = process_chunk(chunk_file)
    final_freq_dist.update(freq_dist)

# Filter the vocabulary based on a frequency threshold
frequency_threshold = 2210  # Adjust this threshold
vocab = [word for word, freq in final_freq_dist.items() if freq > frequency_threshold]

# Save the new vocabulary
vocab_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/reduced_vocab.txt'
with open(vocab_path, 'w') as f:
    f.write("\n".join(vocab))

print(f"Vocabulary size after reduction: {len(vocab)}")


Processing chunks: 100%|██████████| 12/12 [02:19<00:00, 11.62s/it]


Vocabulary size after reduction: 7161


In [28]:
vocab_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/reduced_vocab.txt'
vocab = load_vocabulary(vocab_path)
print(len(vocab))

7161


### 2. I noticed some letters present in the vocab which can be considered as stop words ... for eg there are alphabets like `e` and all which are just letters. I will remove those from the vocabulary.

In [29]:
# List of stop words
stop_words = [
    'given', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
    'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
    'u', 'v', 'w', 'x', 'y', 'z'
]

# Removing stop words from the vocabulary
filtered_vocab = [word for word in vocab if word not in stop_words]

print(len(filtered_vocab))

7140


### 3. Since the corpus is made from research papers things like `et.al.` will be present. we can remove those as well.

In [30]:
# List of terms to remove
terms_to_remove = ['et', 'al', 'ie', 'eg', 'etc', 'aka', 'viz', 'cf', 'nb', 'pm', 'vs']

# Remove the terms from the vocabulary
filtered_vocab = [word for word in filtered_vocab if word not in terms_to_remove]

len(filtered_vocab)

7134

### Now i will store this filtered vocab.

In [31]:
# Save the filtered vocabulary
filtered_vocab_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/filtered_vocab.txt'
with open(filtered_vocab_path, 'w') as f:
    f.write("\n".join(filtered_vocab))

### Now i will reduce the size of the cooccurrence matrix as well.

In [2]:
import h5py
import numpy as np
import scipy.sparse as sp
import pandas as pd
from tqdm import tqdm

# Load the original co-occurrence matrix (sparse format)
co_occurrence_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/final_cooccurrence_matrix.h5'
with h5py.File(co_occurrence_path, 'r') as f:
    data = f['data'][:]
    indices = f['indices'][:]
    indptr = f['indptr'][:]
    shape = f.attrs['shape']

# Rebuild the sparse co-occurrence matrix (CSR format)
co_occurrence_matrix = sp.csr_matrix((data, indices, indptr), shape=shape)

# Load the filtered vocabulary
filtered_vocab_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/filtered_vocab.txt'
with open(filtered_vocab_path, 'r') as file:
    filtered_vocab = [line.strip() for line in file]

# Create a mapping from vocabulary words to their indices
vocab_index = {word: i for i, word in enumerate(filtered_vocab)}

# Create a new co-occurrence matrix based on the filtered vocabulary
filtered_matrix = sp.lil_matrix((len(filtered_vocab), len(filtered_vocab)), dtype=np.float32)

# Populate the filtered co-occurrence matrix based on the original matrix with progress bar
for word, new_index in tqdm(vocab_index.items(), desc="Building filtered co-occurrence matrix", total=len(vocab_index)):
    original_index = vocab_index.get(word)  # Get the index of the word in the original matrix

    if original_index is not None:
        # Copy relevant row and column from the original matrix
        filtered_matrix[new_index, :] = co_occurrence_matrix[original_index, :].toarray()[0, list(vocab_index.values())]
        filtered_matrix[:, new_index] = co_occurrence_matrix[:, original_index].toarray()[list(vocab_index.values()), 0]

# Convert the matrix to CSR for efficiency
filtered_matrix_csr = filtered_matrix.tocsr()

# Save the new filtered co-occurrence matrix
filtered_co_occurrence_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/filtered_cooccurrence_matrix.h5'
with h5py.File(filtered_co_occurrence_path, 'w') as f:
    f.create_dataset('data', data=filtered_matrix_csr.data, compression='gzip')
    f.create_dataset('indices', data=filtered_matrix_csr.indices, compression='gzip')
    f.create_dataset('indptr', data=filtered_matrix_csr.indptr, compression='gzip')
    f.attrs['shape'] = filtered_matrix_csr.shape

print(f"Filtered co-occurrence matrix saved at: {filtered_co_occurrence_path}")


Building filtered co-occurrence matrix: 100%|██████████| 7134/7134 [31:37<00:00,  3.76it/s]

Filtered co-occurrence matrix saved at: /content/drive/MyDrive/NLP Assignments/Assignment_02/filtered_cooccurrence_matrix.h5


In [36]:
file_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/reduced_cooccurrence_matrix.h5'
view_submatrix(file_path, row_start=6000, col_start=5000, size = 10)

10x10 Submatrix:
[[  8.   4.   2.   5.   5.   6.  10.   5.   7.   9.]
 [  7.  27.  11.  24.  18.  20.  13.  37.  17.  19.]
 [ 21.   2.  35.   3.   0. 146.   3.  10.   3.  24.]
 [  0.  37.   2.   8. 152.   1.  15.   5.   8.   3.]
 [  7.   0.   1.   1.   7.   3.   1.   0.   0.  12.]
 [ 21.  27.   4.  15.   8.   5.  16.   7.   3.  25.]
 [  6.  11.  10.  13.  31.   1.  71.  15.  24.   6.]
 [  3.   2.  13.   6.   7.  15.   4.   0.   9.  62.]
 [  3.   1.  30.   4.  15.   3.   7.   5.   3.   4.]
 [ 10.  49.  14.   9.  19.  13.  25.  24.   3.   4.]]


In [35]:
import h5py
import scipy.sparse as sp

# Load the filtered co-occurrence matrix
filtered_co_occurrence_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/reduced_cooccurrence_matrix.h5'

with h5py.File(filtered_co_occurrence_path, 'r') as f:
    data = f['data'][:]
    indices = f['indices'][:]
    indptr = f['indptr'][:]
    shape = f.attrs['shape']

# Rebuild the sparse co-occurrence matrix (CSR format)
filtered_matrix = sp.csr_matrix((data, indices, indptr), shape=shape)

# Calculate the total number of elements and the number of non-zero elements
total_elements = filtered_matrix.shape[0] * filtered_matrix.shape[1]
non_zero_elements = filtered_matrix.nnz

# Calculate the number of zeros and the percentage of zeros
number_of_zeros = total_elements - non_zero_elements
percentage_of_zeros = (number_of_zeros / total_elements) * 100

print(f"Total elements: {total_elements}")
print(f"Non-zero elements: {non_zero_elements}")
print(f"Percentage of zeros: {percentage_of_zeros:.2f}%")


Total elements: 49000000
Non-zero elements: 30923113
Percentage of zeros: 36.89%


In [32]:
from google.colab import drive
drive.mount('/content/drive')

import os
import json
import numpy as np
import scipy.sparse as sp
import h5py
from tqdm import tqdm

# Load the filtered vocabulary (7000+ words)
def load_vocabulary(vocab_path):
    with open(vocab_path, 'r') as file:
        vocab = [line.strip() for line in file]
    return vocab

# Function to process a single JSON chunk file and build the co-occurrence matrix
def process_single_file(file_path, vocab_index, window_size, output_path):
    vocab_size = len(vocab_index)
    cooccurrence_matrix = sp.lil_matrix((vocab_size, vocab_size), dtype=np.float32)

    # Read the JSON file chunk
    with open(file_path, 'r') as file:
        data = json.load(file)

    # Process each document in the current JSON file chunk
    with tqdm(total=len(data), desc=f'Processing {os.path.basename(file_path)}') as pbar:
        for document in data:
            # Filter and index the tokens based on the selected vocabulary
            token_indices = [vocab_index[token] for token in document if token in vocab_index]

            # Update the co-occurrence matrix
            for i, token_idx in enumerate(token_indices):
                start_index = max(0, i - window_size)
                end_index = min(len(token_indices), i + window_size + 1)

                # Update co-occurrence for previous and future tokens in the window
                for j in range(start_index, i):
                    cooccurrence_matrix[token_idx, token_indices[j]] += 1
                for j in range(i + 1, end_index):
                    cooccurrence_matrix[token_idx, token_indices[j]] += 1

            pbar.update(1)

    # Convert to CSR format for efficient storage
    cooccurrence_matrix_csr = cooccurrence_matrix.tocsr()

    # Store the co-occurrence matrix in HDF5 format
    output_file = os.path.join(output_path, f'cooccurrence_matrix_{os.path.basename(file_path).split(".")[0]}.h5')
    with h5py.File(output_file, 'w') as f:
        f.create_dataset('data', data=cooccurrence_matrix_csr.data, compression='gzip')
        f.create_dataset('indices', data=cooccurrence_matrix_csr.indices, compression='gzip')
        f.create_dataset('indptr', data=cooccurrence_matrix_csr.indptr, compression='gzip')
        f.attrs['shape'] = cooccurrence_matrix_csr.shape

    # Clear memory
    del cooccurrence_matrix
    del cooccurrence_matrix_csr
    del data

    print(f"Co-occurrence matrix for {file_path} saved at: {output_file}")
    return output_file

# Function to iterate over all JSON files and build co-occurrence matrices
def process_json_files(json_files_dir, vocab_path, output_path, window_size=4):
    vocab = load_vocabulary(vocab_path)
    vocab_index = {word: i for i, word in enumerate(vocab)}

    # Iterate over all files in the JSON directory
    for json_file in os.listdir(json_files_dir):
        if json_file.endswith('.json'):
            json_file_path = os.path.join(json_files_dir, json_file)
            process_single_file(json_file_path, vocab_index, window_size, output_path)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [33]:

# Path to filtered vocabulary
vocab_path = '/content/drive/MyDrive/NLP Assignments/Assignment_02/filtered_vocab.txt'

# Directory containing JSON corpus chunks
json_files_dir = '/content/drive/MyDrive/NLP Assignments/preprocessed_files'

# Output directory for co-occurrence matrix files
output_path = '/content/drive/MyDrive/NLP Assignments/cooccurrence_matrices/'

# Process all JSON files and build co-occurrence matrices with a window size of 4
process_json_files(json_files_dir, vocab_path, output_path, window_size=4)

Processing chunk_1.json:  60%|██████    | 2843/4711 [10:40<07:01,  4.44it/s]


KeyboardInterrupt: 

In [34]:
import numpy as np
import scipy.sparse as sp
import h5py

# Step 1: Load the original co-occurrence matrix from the HDF5 file
def load_cooccurrence_matrix(hdf5_file):
    with h5py.File(hdf5_file, 'r') as f:
        data = f['data'][:]
        indices = f['indices'][:]
        indptr = f['indptr'][:]
        shape = f.attrs['shape']

        # Reconstruct sparse matrix
        cooccurrence_matrix = sp.csr_matrix((data, indices, indptr), shape=shape)

    return cooccurrence_matrix

# Step 2: Load the original vocabulary (for 1.4 million words)
def load_vocabulary(vocab_file):
    with open(vocab_file, 'r') as file:
        vocab = [line.strip() for line in file]
    return vocab

# Step 3: Sum co-occurrence frequencies for each word
def get_cooccurrence_sums(cooccurrence_matrix):
    # Sum along rows to get the total co-occurrence frequency for each word
    word_cooccurrence_sums = np.array(cooccurrence_matrix.sum(axis=1)).flatten()
    return word_cooccurrence_sums

# Step 4: Rank words by total co-occurrence frequency and get top N words
def select_top_words(cooccurrence_sums, vocab_size):
    # Get indices of top N words based on co-occurrence sums
    top_word_indices = np.argsort(cooccurrence_sums)[-vocab_size:]
    return top_word_indices

# Step 5: Filter the co-occurrence matrix to keep only the top words
def filter_cooccurrence_matrix(cooccurrence_matrix, top_word_indices):
    # Extract rows and columns corresponding to top_word_indices
    reduced_matrix = cooccurrence_matrix[top_word_indices, :][:, top_word_indices]
    return reduced_matrix

# Step 6: Save the reduced co-occurrence matrix and reduced vocabulary
def save_reduced_matrix_and_vocab(reduced_matrix, reduced_vocab, output_matrix_file, output_vocab_file):
    # Save reduced co-occurrence matrix to HDF5
    with h5py.File(output_matrix_file, 'w') as f:
        f.create_dataset('data', data=reduced_matrix.data, compression='gzip')
        f.create_dataset('indices', data=reduced_matrix.indices, compression='gzip')
        f.create_dataset('indptr', data=reduced_matrix.indptr, compression='gzip')
        f.attrs['shape'] = reduced_matrix.shape

    # Save reduced vocabulary to a text file
    with open(output_vocab_file, 'w') as f:
        for word in reduced_vocab:
            f.write(f"{word}\n")

# Main function to reduce co-occurrence matrix and vocabulary by co-occurrence frequency
def reduce_matrix_and_vocab(hdf5_file, vocab_file, output_matrix_file, output_vocab_file, vocab_size):
    # Load the original co-occurrence matrix
    cooccurrence_matrix = load_cooccurrence_matrix(hdf5_file)

    # Load the original vocabulary
    vocab = load_vocabulary(vocab_file)

    # Get co-occurrence sums for each word
    cooccurrence_sums = get_cooccurrence_sums(cooccurrence_matrix)

    # Select top words based on co-occurrence frequency
    top_word_indices = select_top_words(cooccurrence_sums, vocab_size)

    # Filter the matrix to keep only the top words
    reduced_matrix = filter_cooccurrence_matrix(cooccurrence_matrix, top_word_indices)

    # Get the reduced vocabulary
    reduced_vocab = [vocab[i] for i in top_word_indices]

    # Save the reduced matrix and vocabulary
    save_reduced_matrix_and_vocab(reduced_matrix, reduced_vocab, output_matrix_file, output_vocab_file)

# Paths to original matrix, vocab, and reduced output files
original_matrix_file = '/content/drive/MyDrive/NLP Assignments/Assignment_02/final_cooccurrence_matrix.h5'
original_vocab_file = '/content/drive/MyDrive/NLP Assignments/vocabulary.txt'
reduced_matrix_file = '/content/drive/MyDrive/NLP Assignments/Assignment_02/reduced_cooccurrence_matrix.h5'
reduced_vocab_file = '/content/drive/MyDrive/NLP Assignments/Assignment_02/reduced_vocabulary_2.txt'
vocab_size = 7000  # Number of top words to keep

# Run the reduction process
reduce_matrix_and_vocab(original_matrix_file, original_vocab_file, reduced_matrix_file, reduced_vocab_file, vocab_size)


## Co-occurrence Matrix

The co-occurrence matrix used in this assignment is too large to be displayed here directly. You can download or view the matrix using the following link:

[Download Co-occurrence Matrix](https://drive.google.com/file/d/your-file-id/view?usp=sharing)

_Note: This matrix is stored in HDF5 format due to its large size._


## Normalizing the entries using proabilities $\frac {P_{ik}} {P_{jk}}$

$X$      -> Co-occurrence Matrix      <br>
$X_{ij}$ -> Number of times word j occurs in the context of word i. <br>
$X_i = \sum_k X_{ik}$ -> Number of any word appears in the context of word i.<br>
$P_{ij} = P(j|i) = \frac {X_{ij} } {X_i}$ <br>
This gives the probability that the word j occurs in the contex of the word i.

<br>

$\frac {P_{ik}} {P_{jk}} = {P(k|i)} {P(k|j)} $ <br>

<br>
The ratio  $ \frac {P(k|i)} {P(k|j)}$
helps normalize co-occurrence counts by considering the probability of context words with respect to different target words. This normalization emphasizes the relative strength of association between target words, making it easier to distinguish meaningful patterns and relationships.

### Choosing the word for k

**Value of k:** High-Frequency Words (e.g., "the", "and", "of")

**Reason for Choosing This:**

In co-occurrence matrix normalization, selecting high-frequency words as the reference `k` helps address the issue of frequency bias. High-frequency words, being common across various contexts, serve as a stable baseline for comparison. By normalizing co-occurrence counts using these high-frequency words, we adjust for their overwhelming presence and mitigate their disproportionate influence. The ratio of co-occurrence probabilities $ \frac{P(k | i)}{P(k | j)} $ helps us understand the relative strength of the association between the target words `i` and `j` compared to their association with a high-frequency word `k`. This normalization process emphasizes the distinctive relationships between `i` and `j` by neutralizing the impact of common words that might otherwise dominate the matrix. Thus, using high-frequency words ensures that the co-occurrence matrix reflects more meaningful and specific patterns rather than being skewed by the frequent occurrence of generic words.



## Steps for Normalizing Co-occurrence Matrix

1. **Find the Most Frequent Word**:
   Start by summing each row (or column) of the co-occurrence matrix to get the total occurrences of each word across all contexts. The word with the highest total is identified as the most frequent word.

2. **Normalize the Co-occurrence Matrix**:
   Using the most frequent word $ k $, normalize the co-occurrence matrix. The normalization is done by calculating the ratio $ \frac{P(k | i)}{P(k | j)} $, where:
   - $ P(k | i) $ is the probability of word $ k $ occurring in the context of word $ i $.
   - $ P(k | j) $ is the probability of word $ k $ occurring in the context of word $ j $.
   - This step adjusts the co-occurrence counts by considering the probability of context words with respect to different target words.

3. **Remove the Most Frequent Word**:
   Once the normalization is done, remove the row and column corresponding to the most frequent word from the co-occurrence matrix. Also, remove the most frequent word from the vocabulary list, so it no longer influences further analysis.
